# Generated by Django 2.2 on 2021-08-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_name', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True)),
                ('photo', models.ImageField(default='author_img/defaul.jpg', upload_to='author_img/')),
            ],
        ),
    ]
