# Generated by Django 2.2 on 2021-08-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elib_api', '0002_auto_20210805_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
