# Generated by Django 2.2 on 2021-08-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elib_api', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(default='book_cover_img/default.jpg', upload_to='book_cover_img/'),
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='book_file/'),
        ),
    ]
